### ISSUE TITLE
Cannot use GeometryCollection when shapely is installed

### ISSUE THREAD

**Issue by liskin** [cleder/fastkml#100]
Similar to #68.

When shapely is installed, GeometryCollection can't be used:

```
from fastkml import kml
p = kml.Placemark(styleUrl="#normal")
p.geometry = {'type': "GeometryCollection", 'geometries': []}
p.to_string()
```

This fails with `ValueError("Illegal geometry type.")`, but it works just fine when fastkml uses pygeoif.

I'm guessing it's because
https://github.com/cleder/fastkml/blob/9f24722a91315536fff4c12cc1591a6febafad16/fastkml/geometry.py#L43
and then
https://github.com/cleder/fastkml/blob/9f24722a91315536fff4c12cc1591a6febafad16/fastkml/geometry.py#L275
fails because
https://github.com/cleder/fastkml/blob/9f24722a91315536fff4c12cc1591a6febafad16/fastkml/geometry.py#L128
creates a shapely GeometryCollection, not pygeoif one.

**Comment by liskin** [comment]
I finally got around to testing my code with fastkml 1.0a1 and it turns out it just works. shapely geometry is automatically converted to pygeoif geometry via `__geo_interface__` and everything just works. So… nevermind and sorry for the noise. :-)

**Comment by cleder** [comment]
Thanks for testing and letting me know, :-) Much appreciated!

**Comment by liskin** [comment]
Seems like `__geo_interface__` stuff doesn't work any more in 1.0.alpha.6. Looks like it's now necessary to [manually convert even `pygeoif` objects to `fastkml.geometry` objects](https://github.com/liskin/liscopridge/commit/8b610028b8b84bfe83b4316f3703029e39327948#diff-521dfe0dab9d99f1b4c0b7cdaf0c222ea3b3bd07b1c9a37739c3b8dbf95970ddR126-R133) otherwise one gets errors like these:
```AttributeError: 'GeometryCollection' object has no attribute 'etree_element'```

I wonder if that's intentional?

**Comment by liskin** [comment]
Sure:

```python
#!/usr/bin/env python3

import fastkml
import pygeoif.geometry

g = pygeoif.geometry.Point(1, 1)
if fastkml.__version__ == "1.0a4":
    p = fastkml.kml.Placemark()
    p.geometry = g
else:
    p = fastkml.kml.Placemark(geometry=g)
print(p.to_string())
```

```console
$ python3 -m venv venv-fastkml-a4
$ python3 -m venv venv-fastkml-a6
$ ./venv-fastkml-a4/bin/pip install 'fastkml == 1.0a4'
$ ./venv-fastkml-a6/bin/pip install 'fastkml == 1.0a6'
$ ./venv-fastkml-a4/bin/python fastkml-interface.py
/tmp/venv-fastkml-a4/lib/python3.11/site-packages/fastkml/config.py:37: UserWarning: Package `lxml` missing. Pretty print will be disabled
  warnings.warn("Package `lxml` missing. Pretty print will be disabled")
<kml:Placemark xmlns:kml="http://www.opengis.net/kml/2.2"><kml:visibility>1</kml:visibility><kml:Point><kml:coordinates>1.000000,1.000000</kml:coordinates></kml:Point></kml:Placemark>
$ ./venv-fastkml-a6/bin/python fastkml-interface.py 
/tmp/venv-fastkml-a6/lib/python3.11/site-packages/fastkml/config.py:37: UserWarning: Package `lxml` missing. Pretty print will be disabled
  warnings.warn("Package `lxml` missing. Pretty print will be disabled")
Traceback (most recent call last):
  File "/tmp/fastkml-interface.py", line 13, in <module>
    print(p.to_string())
          ^^^^^^^^^^^^^
  File "/tmp/venv-fastkml-a6/lib/python3.11/site-packages/fastkml/base.py", line 116, in to_string
    self.etree_element(
  File "/tmp/venv-fastkml-a6/lib/python3.11/site-packages/fastkml/kml.py", line 1757, in etree_element
    element.append(self._geometry.etree_element())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Point' object has no attribute 'etree_element'
```

So yeah I can pretty confidently say the examples from https://fastkml.readthedocs.io/en/latest/usage_guide.html no longer work :-)

**Comment by cleder** [comment]
There was a lot of refactoring in `fastkml.geometry` (it has developed into a mess, what was the developer thinking :exploding_head: ) Check what you pass against the type annotations, this probably changed during this refactor.
Thanks for your support, I will take a look, writing a guide migrating from 0 to 1 is on my radar, just not a priority right now

**Comment by cleder** [comment]
#239 is probably the place to look

**Comment by cleder** [comment]
closing this in favour of #264

**Comment by cleder** [comment]
@liskin the latests commit brings back the option to create a feature with just a geometry to support backwards compatibility

**Comment by liskin** [comment]
> @liskin the [commit](https://github.com/cleder/fastkml/commit/40e60be53dd8919032f5a9f2884cc4e713054492) brings back the option to create a feature with just a geometry to support backwards compatibility

Right, it does indeed. ♥
Unfortunately now one can't use `fastkml.geometry` objects for the `Placemark` `geometry` any more. Not sure if that's intended… 🙂
(I mean I don't want that, I want to be passing shapely/pygeoif data, but I think you perhaps wanted to support both?)

And then there are some vaguely related issues:
* `geometry` needs to be passed to the `Placemark` constructor because it's a read-only property without a setter
* `style_url`, on the other hand, can now only be set using the property setter, as the constructor argument assumes it's a `StyleUrl` class, whereas the property setter converts it from a string

And then I commented on 2 commits of yours pointing out other random breakages (XML namespaces, NetworkLink having no Link).

**Comment by liskin** [comment]
These are the changes I had to make to make my project's tests pass locally:
* https://github.com/cleder/fastkml/commit/8ba227a84f17d9a858b254f868317831a546fb17
* https://github.com/cleder/fastkml/commit/3222469d2aff3bf02c644db0e35c37701a922969
* https://github.com/liskin/liscopridge/commit/5dbd6f3a4e949f7ad4adc7f20d1f72cbc43da01e

Shall I open a PR from https://github.com/cleder/fastkml/compare/develop...liskin:fastkml:fixes?

**Comment by cleder** [comment]
PRs are always welcome ;-)

**Comment by cleder** [comment]
The current develop (I have not cut a release for this yet) reintroduces the ability to pass a shapely or pygeoif (or anything else that supports the `__geo_interface__` protocol) as the `geometry` to `placemark`, or a `fastkml.geometry` kml object as `kml_geometry`.

I can reintroduce a geometry property getter and setter on feature if this is needed (although probably under another name to avoid confusion, like geo_geometry)

**Comment by cleder** [comment]
I made some 'questionable' decisions for shortcuts 10 years ago, based on a use case I had back then. I never imagined it would have north of [100K downloads](https://www.pepy.tech/projects/fastkml) a month, in the first few years I was proud when it had 75 per month (IIRC) :smiley: 

Version 1.0 should be more consistent, easier to work with and to contribute to.

I appreciate your continuing contributions, your comments are very valuable to give me insights what users want to get out of this package :+1:
