### ISSUE TITLE
Python 3 use f-Strings

### ISSUE THREAD

**Issue by cleder** [cleder/fastkml#138]
convert the legacy `%` and `.format` into f-strings.

https://libcst.readthedocs.io/en/latest/codemods_tutorial.html 
https://github.com/ikamensh/flynt
https://github.com/asottile/pyupgrade#f-strings

use the python3 branch as base https://github.com/cleder/fastkml/tree/python3

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this?
