### ISSUE TITLE
Type annotate fastkml.data

### ISSUE THREAD

**Issue by cleder** [cleder/fastkml#189]
Correct and improve the type annotations of the file `fastkml/data.py` so that the `pyproject.toml` directive to exclude this file from `mypy` can be dropped

**Comment by ramonsaraiva** [comment]
hey @cleder - I'm working on the type annotations for the `data` file, will have a PR soon.

**Comment by cleder** [comment]
https://towardsdatascience.com/12-beginner-concepts-about-type-hints-to-improve-your-python-code-90f1ba0ac49
