### ISSUE TITLE
Use Python Enums for kmlEnum

### ISSUE THREAD

**Issue by cleder** [cleder/fastkml#194]
Use [python enum](https://realpython.com/python-enum/) for [KML Field enums](https://developers.google.com/kml/documentation/kmlreference#kml-fields) to be more [literal](https://mypy.readthedocs.io/en/stable/literal_types.html).
This allows to type check for [Exhaustiveness](https://adamj.eu/tech/2022/10/14/python-type-hints-exhuastiveness-checking/).

**Comment by Aamir-Ansari-almost** [comment]
I would like to work on this issue

**Comment by cleder** [comment]
Good hunting ;-)
