### ISSUE TITLE
Modernize packaging 

### ISSUE THREAD

**Issue by cleder** [cleder/fastkml#251]
Instead of `setup.py` the packaging configuration should be done with `pyproject.toml`

https://github.com/gvalkov/setuptools-py2cfg to convert setup.py to a config file and https://github.com/abravalheri/ini2toml to convert the `setup.cfg` file into `pyproject.toml` check the results with https://github.com/abravalheri/validate-pyproject and https://github.com/kieran-ryan/pyprojectsort

**Comment by whisk** [comment]
Hi @cleder, please see the PR #252
