### ISSUE TITLE
Use arrow instead of dateutil

### ISSUE THREAD

**Issue by cleder** [cleder/fastkml#254]
Refactor to use [arrow](https://github.com/arrow-py/arrow) instead of [dateutil](https://github.com/dateutil/dateutil)

Arrow and dateutil are both Python libraries for working with dates and times, and each has its own set of features and advantages. Here are some reasons you might prefer Arrow over dateutil:

1. Simpler and More Intuitive API: Arrow is designed to have a simple and intuitive API. Many developers find it easier to use and more straightforward, especially for common date and time operations.
2. Immutable and Chainable: Arrow objects are immutable, which means that operations on Arrow objects return new Arrow objects without modifying the original. This immutability can make code more predictable and less error-prone. It also allows for method chaining, making it easy to perform multiple operations in a single line of code.
3. Time Zones Handling: Arrow provides a more intuitive and developer-friendly approach to working with time zones. It uses the IANA Time Zone Database for time zone information, and it provides better support for operations involving different time zones. 
4. Consistent Behavior: Arrow attempts to provide consistent behavior across different platforms and environments, reducing the likelihood of platform-specific bugs or discrepancies.
5. Extensive Documentation and Community: Arrow has thorough documentation and an active community, which can be helpful if you run into issues or need assistance with complex date and time operations.

**Comment by ha36d** [comment]
Can I work on the issue?
