### ISSUE TITLE
StyleMap -- normal and highlight arguments are ignored

### ISSUE THREAD

**Issue by c-nichols** [cleder/fastkml#29]
Hi there,

The `normal` and `highlight` keyword args to `StyleMap`'s init method are ignored -- see here: https://github.com/cleder/fastkml/blob/master/fastkml/styles.py#L147

It looks like the only way to create one of these right now is to subclass `StyleMap`?

I'm not sure what the intended usage is, but it seems like either A) a fix or B) a documentation update (and removal of those kwargs) is in order.

Let me know if I can help.

Thanks!
Colin

**Comment by cleder** [comment]
OOPS. Can you fix and PR?
