### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by araichev** [cleder/fastkml#33]
Hi there, when i use fastkml in Python 3 to parse [this sample KML file from Google](https://developers.google.com/kml/documentation/KML_Samples.kml), i get the warning ``WARNING:fastkml.kml:No geometries found``.  What's going on here?

**Comment by cleder** [comment]
it works for me:

import fastkml
f = open('/home/christian/Downloads/KML_Samples.kml', 'r')
s = f.read()
k = fastkml.KML()
k.from_string(s)
list(list(list(k.features())[0].features())[0].features())[0].geometry

can you send any traceback?

**Comment by araichev** [comment]
Ah yes, i can access that particular geometry as well, but i still get the warning i mentioned.  See [4] below.

```python
Python 3.4.2 (default, Jan  7 2015, 11:57:48) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import fastkml

In [2]: with open('data/example_01/doc.kml') as src:
   ...:     kml_str = src.read()
   ...:     

In [3]: k = fastkml.KML()

In [4]: k.from_string(kml_str)
No geometries found

In [5]: list(list(list(k.features())[0].features())[0].features())[0].geometry
Out[5]: <shapely.geometry.point.Point at 0x10bc68d68>

In [6]: 
```

**Comment by cleder** [comment]
fastkml does not handle NULL geometries
