### ISSUE TITLE
Problems creating document

### ISSUE THREAD

**Issue by Skippern** [cleder/fastkml#34]
I have problems creating documents, following the code snippets in the example. I have geometries from Shapely I need to visualise for debugging, and thought KML to Google Earth as a good choice for this.

```
Traceback (most recent call last):
  File "./gpxtest.py", line 459, in <module>
    country = test_relation(testing)
  File "./gpxtest.py", line 243, in test_relation
    mk_kml(test, id, name)
  File "./gpxtest.py", line 265, in mk_kml
    d = klm.Document(ns, str(id), name, 'Border visualisation')
AttributeError: 'KML' object has no attribute 'Document'
```

Suspect I will get the same errors for `Folder` and `geometry`

Code block in question:
```python
def mk_kml(object, id, name):
    print "Creating KML"
    try:
        klm = kml.KML()
        ns = '{http://www.opengis.net/kml/2.2}'
        d = klm.Document(ns, str(id), name, 'Border visualization')
        klm.append(d)
        f1 = klm.Folder(ns, str(id), 'Boundaries', 'Border visualization')
        d.append(f1)
        p = klm.Placemark(ns, str(id), name, 'Border of {0}'.format(name))
        p.geometry = object
        f1.append(p)
        filename = "./klm/"+id+"_"+name.replace(" ", "_")+".kml"
        fil = open(filename, 'w')
        fil.write(klm.to_string(prettyprint=True))
        fil.close()
        print "KML Saved"
    except:
        print "Failed to create KML"
        raise
```

**Comment by cleder** [comment]
>>> from fastkml import kml
No handlers could be found for logger "fastkml.config"
>>> klm = kml.KML()
>>> ns = '{http://www.opengis.net/kml/2.2}'
>>> d = kml.Document(ns, str(id), name, 'Border visualization')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'name' is not defined
>>> klm.append(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'd' is not defined
>>> f1 = kml.Folder(ns, str(id), 'Boundaries', 'Border visualization')
>>> d.append(f1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'd' is not defined
>>> p = kml.Placemark(ns, str(id), name, 'Border of {0}'.format(name))

**Comment by cleder** [comment]
>>> from fastkml import kml
>>> from pygeoif import Point
>>> obj = Point(1,1)
>>> id = '123'
>>> name = 'some name'
>>> klm = kml.KML()
>>> ns = '{http://www.opengis.net/kml/2.2}'
>>> d = kml.Document(ns, str(id), name, 'Border visualization')
>>> klm.append(d)
>>> f1 = kml.Folder(ns, str(id), 'Boundaries', 'Border visualization')
>>> d.append(f1)
>>> p = kml.Placemark(ns, str(id), name, 'Border of {0}'.format(name))
>>> p.geometry = obj
>>> f1.append(p)
>>> klm.to_string(prettyprint=True)
`u'<kml:kml xmlns:kml="http://www.opengis.net/kml/2.2"><kml:Document id="123"><kml:name>some name</kml:name><kml:description>Border visualization</kml:description><kml:visibility>1</kml:visibility><kml:Folder id="123"><kml:name>Boundaries</kml:name><kml:description>Border visualization</kml:description><kml:visibility>1</kml:visibility><kml:Placemark id="123"><kml:name>some name</kml:name><kml:description>Border of some name</kml:description><kml:visibility>1</kml:visibility><kml:Point><kml:coordinates>1.000000,1.000000</kml:coordinates></kml:Point></kml:Placemark></kml:Folder></kml:Document></kml:kml>'`

**Comment by cleder** [comment]
there are some issues with your code, typo `klm` instead of `kml`, `object` is a reserved word, the blind except hides all errors inside the block
