### ISSUE TITLE
Feature Request: pass optional dictionary of namespaces and optional doc type string

### ISSUE THREAD

**Issue by wesley-murray** [cleder/fastkml#346]
I extended the KML class so I could add a from_geojson function. Ideally this concept can be taken further to include other types such as shape files. The raw data formats dont have kml specific logic like xml doc type and namespaces. It would be very helpful if the to_string or constructor method had optional args that allow you to pass on the doctype and a dictionary of namespaces. The namespaces would also need to be passed along to the etree_element function. I had good results with this in my case.

In the below example I used inheritance to overwrite the parent. It assumes use of LXML.
```
def to_string(self, prettyprint=False, namespaces=None, doctype='<?xml version="1.0" encoding="UTF-8"?>') -> str:
        """Returns the KML object as a string."""
        return etree.tostring(
            self.etree_element(namespaces=namespaces),
            encoding="utf-8",
            pretty_print=prettyprint,
            doctype=doctype,
        ).decode("UTF-8")
```

**Comment by HazemAbdo** [comment]
@cleder I'd like to work on this feature under Hacktoberfest. Can you please assign it to me?

**Comment by cleder** [comment]
Please have a look at the [contributing guidelins](https://github.com/cleder/fastkml/blob/develop/docs/contributing.rst).

**Comment by cleder** [comment]
I think instead of adding it to the `to_string` method, it would be better to add a `save` method to `fastkml.kml.KML`  like the `parse` method, taking the file or filename to write to. I don't think you will need to pass the namespaces as @wesley-murray sugested, they are already present on the object.

**Comment by apurvabanka** [comment]
@cleder I would like to give this a try. Can you assign me this issue?

**Comment by apurvabanka** [comment]
@cleder Do we want to add "doctype" as a input parameter while trying to parse a KML file? 
OR 
Do we want to add a "save" functionality with "doctype" as an input parameter?

**Comment by cleder** [comment]
@wesley-murray what is the need for `namespaces`? When you create a fastkml object it always has `name_spaces` defined, defaulting to `config.NAME_SPACES`

**Comment by apurvabanka** [comment]
created draft PR for this issue https://github.com/cleder/fastkml/pull/378
