### ISSUE TITLE
No way to detect 'No geometries found' errors

### ISSUE THREAD

**Issue by hyperknot** [cleder/fastkml#35]
On the attached file, fastkml throws a warning message: 'No geometries found' from Placemark / from_element.

At the moment, there is no way to detect this error scenario, so a gpsbabel cleaning could run. It'd be important to raise an error and not just log a warning in such case.

[kml.zip](https://github.com/cleder/fastkml/files/187143/kml.zip)

**Comment by IanLee1521** [comment]
Any chance you might be willing to replace the attached zip with a link to a gist?

**Comment by hyperknot** [comment]
That's a 200 kb, 5000 line long file, if you'd really like I can put it up, but I'm not sure it's a good idea.

**Comment by hyperknot** [comment]
I did a PR which allowed me to detect the parsing error, might not be the thing you'd like in the library, but at least it signals that the file isn't working in fastkml.
https://github.com/cleder/fastkml/pull/36

**Comment by hyperknot** [comment]
Found a smaller example file, uploaded to gist:
https://gist.github.com/hyperknot/2fc06a3fecb98f07f761

**Comment by hyperknot** [comment]
Found out the real issue here is not supporting gx:Track elements, closing this one.
