### ISSUE TITLE
ETA for new release in PyPi?

### ISSUE THREAD

**Issue by fitoprincipe** [cleder/fastkml#357]
(Just asking) I see that Milestone `v.1.0` is ~80%, but I also see that most of the remaining improvements are related to tests and coverage. The only behavior issue is https://github.com/cleder/fastkml/issues/355 which is actually solved. I think it'd be very nice (and helpful) to see a new release in PyPi ([latest version](https://pypi.org/project/fastkml/) there is from 2021).

**Comment by cleder** [comment]
1.0.a13 published
