### ISSUE TITLE
Broken 1.0.0

### ISSUE THREAD

**Issue by roniemartinez** [cleder/fastkml#394]
Just updated from 0.12 to 1.0.0 and now getting the following errors when using `parse()`

```
  File "src/lxml/etree.pyx", line 3701, in lxml.etree._Validator.assert_
AssertionError: Element '{http://www.opengis.net/kml/2.2}Style': This element is not expected. Expected is one of ( {http://www.opengis.net/kml/2.2}Schema, {http://www.opengis.net/kml/2.2}AbstractFeatureGroup, {http://www.google.com/kml/ext/2.2}Tour, {http://www.opengis.net/kml/2.2}Document, {http://www.opengis.net/kml/2.2}Folder, {http://www.opengis.net/kml/2.2}Placemark, {http://www.opengis.net/kml/2.2}NetworkLink, {http://www.opengis.net/kml/2.2}GroundOverlay, {http://www.opengis.net/kml/2.2}ScreenOverlay, {http://www.opengis.net/kml/2.2}PhotoOverlay )., line 7
```

When using `from_string()`, `features` is empty.

**Comment by cleder** [comment]
Your KML does not validate against the XML Schema.
You can read it without validations by passing `validate=False` or `strict=False` to the parse method

```python
from fastkml.kml import KML
doc = KML.parse('path/to/your/file.kml', strict=False)
# or
doc = KML.parse('path/to/your/file.kml', validate=False)
```

**Comment by roniemartinez** [comment]
@cleder Thanks but I've already tried all of these.

```python
postcode_kml.from_string("<KML string>" strict=False)
postcode_kml.parse('path/to/your/file.kml', strict=False)
postcode_kml.parse('path/to/your/file.kml', validate=False)
```

All of them return an empty `.features` list

```
    document = postcode_kml.features[0]
               ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

For reference, we are reading this KML file: https://www.doogal.co.uk/kml/PostcodeDistricts.kml

**Comment by roniemartinez** [comment]
@cleder I think I found the issue now.

With this version, we can no longer create an instance like this as `from_string()` returns a new object.

```python
postcode_kml = kml.KML()
postcode_kml.from_string(kml_file.read())
```
Instead:

```python
postcode_kml = kml.KML.from_string(kml_file.read())
```

**Comment by cleder** [comment]
Thanks, I added this to the documentation:
https://github.com/cleder/fastkml/blob/develop/docs/upgrading.rst

**Comment by cleder** [comment]
@roniemartinez when you find other issues migrating to 1.0, please open an issue or add your findings here ;-)

**Comment by roniemartinez** [comment]
@cleder Sure thanks 🙇
