### ISSUE TITLE
Add more details to the documentation

### ISSUE THREAD

**Issue by nicbou** [cleder/fastkml#47]
The current documentation about reading a file offers almost no information about how to read different parts of a KML file. Likewise, the reference guide gives no information about what to do with Placemarks.

For instance, this is the file I am trying to parse. Based on the quick tutorial, I can get the Placemark, but I can't do anything with it and all the attributes are set to None.

```
<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom"><Document><name>2016-07-17T11:19:39Z</name>
<Placemark>
<gx:Track>

<when>2016-07-17T11:19:39Z</when>
<gx:coord>13.4410151 52.5321779 0.0</gx:coord>

<when>2016-07-17T11:20:48Z</when>
<gx:coord>13.4445348 52.52911408 66.0</gx:coord>

<when>2016-07-17T11:20:54Z</when>
<gx:coord>13.444335 52.5292497 0.0</gx:coord>

<when>2016-07-17T11:21:10Z</when>
<gx:coord>13.4443962 52.5291495 0.0</gx:coord>
```

**Comment by cleder** [comment]
the `gx:` namespace is currently not implemented and  gets dropped

**Comment by cleder** [comment]
Currently, the only major feature missing for the full Google Earth experience is the gx extension. This will most likely be added after the 1.0 version release.

**Comment by ElusiveTau** [comment]
I'm interested in reading a kml file for the coordinates of the placemarks. Based on what you've said a while back (that gx: namespace is not implemented), does this mean that it's not presently possible to get the coordinates of a placemark?

**Comment by cleder** [comment]
placemarks are implemented. -> https://github.com/cleder/fastkml/blob/master/fastkml/test_main.py#L364

**Comment by withoutwaxaryan** [comment]
Here's a detailed article on using Fastkml : https://medium.com/@wwaryan/the-definite-only-guide-to-fastkml-58b8e19b8454
