### ISSUE TITLE
TypeError (TypeError: type must be one of 'string', 'int', 'uint', 'short', 'ushort', 'float', 'double', 'bool')

### ISSUE THREAD

**Issue by wizardofozzie** [cleder/fastkml#48]
`No handlers could be found for logger "fastkml.config"
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/AA78F2EC-3EE8-40F4-A318-8A9AB1BCB5FF/Pythonista3/Documents/ceid-fixer/fkml.py", line 8, in <module>
    k.from_string(doc)
  File "/private/var/mobile/Containers/Shared/AppGroup/AA78F2EC-3EE8-40F4-A318-8A9AB1BCB5FF/Pythonista3/Documents/site-packages/fastkml/kml.py", line 101, in from_string
    feature.from_element(document)
  File "/private/var/mobile/Containers/Shared/AppGroup/AA78F2EC-3EE8-40F4-A318-8A9AB1BCB5FF/Pythonista3/Documents/site-packages/fastkml/kml.py", line 1001, in from_element
    s.from_element(schema)
  File "/private/var/mobile/Containers/Shared/AppGroup/AA78F2EC-3EE8-40F4-A318-8A9AB1BCB5FF/Pythonista3/Documents/site-packages/fastkml/kml.py", line 1359, in from_element
    self.append(sftype, sfname, sfdisplay_name)
  File "/private/var/mobile/Containers/Shared/AppGroup/AA78F2EC-3EE8-40F4-A318-8A9AB1BCB5FF/Pythonista3/Documents/site-packages/fastkml/kml.py", line 1337, in append
    "type must be one of ""'string', 'int', 'uint', 'short', "
TypeError: type must be one of 'string', 'int', 'uint', 'short', 'ushort', 'float', 'double', 'bool'
`

**Comment by wizardofozzie** [comment]
`doc.kml` is [here](https://github.com/wizardofozzie/CEID2016/blob/master/doc.kml)

Running under py2&3 (no lxml since I'm using iOS Pythonista 3)

**Comment by wizardofozzie** [comment]
Workaround is as follows:
```
    def append(self, type, name, displayName=None):
        """
        append a field.
        The declaration of the custom field, must specify both the type
        and the name of this field.
        If either the type or the name is omitted, the field is ignored.

        The type can be one of the following:
            string
            int
            uint
            short
            ushort
            float
            double
            bool

        <displayName>
        The name, if any, to be used when the field name is displayed to
        the Google Earth user. Use the [CDATA] element to escape standard
        HTML markup.
        """
        allowed_types = [
            'string', 'int', 'uint', 'short', 'ushort',
            'float', 'double', 'bool'
        ]
        # if type not in allowed_types:
        #     raise TypeError(
        #         "type must be one of ""'string', 'int', 'uint', 'short', "
        #         "'ushort', 'float', 'double', 'bool'"
        #     )
        # else:
        #     # TODO explicit type conversion to check for the right type
        #     pass
        self._simple_fields.append({'type': str(type), 'name': name,
                                    'displayName': displayName})
```

**Comment by davepeck** [comment]
@wizardofozzie The `doc.kml` that you linked to is actually invalid KML, which is why `fastkml` is unhappy. 

Specifically, `doc.kml` has several `SimpleField` declarations where the `type="wstring"`. But the official KML documentation is pretty clear on this point; see: https://developers.google.com/kml/documentation/extendeddata#adding-typed-data-to-a-feature

I also ran into a set of KML files -- in my case, directly from `census.gov` -- with invalid `SimpleField` types. I ended up writing a derived class of `kml.KML` as follows:

```python
def LenientKML(kml.KML):
    def append(self, type, name, displayName=None):
        if not self.type_is_valid(type):
            type = self.fix_type(type)
        return super(LenientXML, self).append(type, name, displayName=displayName)

   def type_is_valid(self, type):
        return type in ['string', 'int', 'uint', 'short', 'ushort', 'float', 'double', 'bool']
   
    def fix_type(self, type):
        return type
```

In your case, you might implement:
```python
class MyLenientKML(LenientKML):
    def fix_type(self, type):
        if type is 'wstring':
            type = 'string'
        return type
```
