### ISSUE TITLE
Load KML as shapely polygon

### ISSUE THREAD

**Issue by Skippern** [cleder/fastkml#49]
I am looking for a way to create a shapely polygon from existing KML files, my script is currently getting geographical information for comparison from `Overpass`, and stores the polygons as KML as well as running the comparison. Since some of the polygons are huge, it takes hours creating all the polygons. If the script could load reoccurring polygons from the stored KML files I would have a huge speed increase in the script, and be able to compare much more data. I would like to, if possible, avoid need for converting the KML's with external software (`ogr2ogr` conversion to `.wkb` for example) as relying on external executions like that are likely to interrupt the automated workflow.

**Comment by cleder** [comment]
and your question is?

**Comment by Skippern** [comment]
Would it be possible to have an `kml.loads` function that returns a `shapely`-object of the stored KML object from file? Similar to shapely's `wks.loads` or `wkb.loads`

**Comment by cleder** [comment]
each placemark has a geometry attribute which is a shapely object if shapely is installed.
https://fastkml.readthedocs.io/en/latest/usage_guide.html
