### ISSUE TITLE
Problems with unix timestamps

### ISSUE THREAD

**Issue by Colleoni** [cleder/fastkml#53]
Hi,

I have encountered problems parsing unix timestamp.
The library uses the entire timestamp values as year and as result I obtain a

`ValueError: year is out of range`

in my case the problem occurs with parameters like:

`<TimeStamp><when>1483258435</when></TimeStamp>`

Luca

**Comment by cleder** [comment]
according to https://developers.google.com/kml/documentation/kmlreference#timeprimitive and 
https://www.w3.org/TR/xmlschema-2/#isoformats a unix timestamp is not a valid TimeStamp attribute. i recommend to convert these to a valid iso format date time in a preprocessing step
