### ISSUE TITLE
No handlers could be found for logger "fastkml.config"

### ISSUE THREAD

**Issue by Winterflower** [cleder/fastkml#54]
Hello fastkml developers,
I'm on Python 2.7 and trying to import kml into my shell. Unfortunately, I am getting the message below

>>> from fastkml import kml
No handlers could be found for logger "fastkml.config"

I see that some parts of the build https://travis-ci.org/cleder/fastkml/jobs/220557807 are failing for this reason as well. 

Edit: I should clarify that I was still able to import kml into my namespace - so this is not a bug. Could the maintainers kindly close this issue. Many thanks!

**Comment by cleder** [comment]
this is only a warning, it works fine without any loggers configured:
```
>>> from fastkml import kml
No handlers could be found for logger "fastkml.config"
>>> dir(kml)
['Data', 'Document', 'ExtendedData', 'Folder', 'Geometry', 'GroundOverlay', 'KML', 'Placemark', 'Schema', 'SchemaData', 'Style', 'StyleMap', 'StyleUrl', 'TimeSpan', 'TimeStamp', 'UntypedExtendedData', 'UntypedExtendedDataElement', '_BaseObject', '_Container', '_Feature', '_Overlay', '_StyleSelector', '_TimePrimitive', '_XMLObject', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'atom', 'config', 'date', 'datetime', 'dateutil', 'etree', 'logger', 'logging', 'urlparse', 'warnings']
>>> k = kml.KML()
>>> k
<fastkml.kml.KML object at 0x7f701a784a90>
>>> 
```
