### ISSUE TITLE
Documentation: How fast is "fast"?

### ISSUE THREAD

**Issue by movermeyer** [cleder/fastkml#56]
When a library claims to be "fast", I immediately look for benchmarks, especially those that compare the library against other Python KML libraries.

It would be a good idea to add benchmarks, similar to the way that libraries like [udatetime](https://github.com/freach/udatetime) and [fastavro](https://github.com/tebeka/fastavro) do.

**Comment by heltonbiker** [comment]
From the README:

"Fast refers to the time you spend to write and read KML files as well as the time you spend to get aquainted to the library or to create KML objects."

So perhaps in the second sense ("fast to learn") it could have been called "QuickKML".

But in the first sense, I also wonder how faster it would be, compared to similar alternatives.
