### ISSUE TITLE
FastKML parsing from files

### ISSUE THREAD

**Issue by whatnick** [cleder/fastkml#57]
FastKML reads KML snippets from strings rather than files. Reading files using Pythons standard document parser makes assumptions about encoding and it the UTF / Unicode encoding string is forwarded to lxml it does not want to parse it and wants to perform its own interpretation or obtain the data as raw bytes. It would be good to extend fastKML to include a from_file method in the parser to circumvent this and pass the file directly to lxml for encoding interpretation etc.

#### This code:

> k = kml.KML()
> with open(track_KML, 'r') as myfile:
>     data=myfile.read().replace('\n', '')
> k.from_string(data)

####  Leads to:

> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-18-38ff5066c61f> in <module>()
>       2 with open(track_KML, 'r') as myfile:
>       3     data=myfile.read().replace('\n', '')
> ----> 4 k.from_string(data)
> 
> c:\python35\lib\site-packages\fastkml\kml.py in from_string(self, xml_string)
>      89             element = etree.fromstring(
>      90                 xml_string,
> ---> 91                 parser=etree.XMLParser(huge_tree=True)
>      92             )
>      93         else:
> 
> src\lxml\lxml.etree.pyx in lxml.etree.fromstring (src\lxml\lxml.etree.c:79593)()
> 
> src\lxml\parser.pxi in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:119053)()
> 
> ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

The error is indicative of encoding conflicts and direct parsing from files will be really useful for my use-cases.

**Comment by LingboTang** [comment]
I met the same problem here.

**Comment by LingboTang** [comment]
@whatnick You shouldn't replace the newline character, you could just do `myfile.read().encode('utf-8')` and you should be able to parse your file through fastkml. Although I think a user shouldn't do this encoding/decoding explicitly, it should be wrapped in their implementation and hide from user. @cleder

**Comment by samifouad** [comment]
> @whatnick You shouldn't replace the newline character, you could just do `myfile.read().encode('utf-8')` and you should be able to parse your file through fastkml. Although I think a user shouldn't do this encoding/decoding explicitly, it should be wrapped in their implementation and hide from user. @cleder

There should be a documentation update with the method you described presented to new users of this. Because right now if you follow along with the starter examples, you get an error only solved by using this snippet.

**Comment by LingboTang** [comment]
@samifouad  I haven't worked with this lib for a while, not sure if they have already updated.

**Comment by answerquest** [comment]
yep, we need a documentation update here: https://fastkml.readthedocs.io/en/latest/usage_guide.html#read-a-kml-file-string

**Comment by galloramiro** [comment]
Agree with the comumentation update

**Comment by withoutwaxaryan** [comment]
Since the documentation hasn't been updated , even for Python 3 + , I wrote a detailed article here : https://medium.com/@wwaryan/the-definite-only-guide-to-fastkml-58b8e19b8454

Cheers!
