### ISSUE TITLE
Explicit Getters?

### ISSUE THREAD

**Issue by LingboTang** [cleder/fastkml#61]
I'm new to fastkml, and I'm using it for parsing kml files. I've read through docs, and you guys has provided well-explained docs for setters. However, after reading through more docs and source code, I didn't find getters explicitly, so my parsing seems very handy and uncomfortable. In fact, in one of the example, you used `getattr` as well. So, I'm requesting adding some explicit getters. So when people are parsing huge kmls, they will feel less uncomfortable.

**Comment by cleder** [comment]
I don't think I understand the request. You can access every attribute in a python class with it's name. e.g. `placemark.geometries` why would you need explicit getters?

**Comment by LingboTang** [comment]
To be more specific, this usage example is going to be a general template for plenty of use cases:

```
def print_child_features(element):
    if not getattr(element, 'features', None):
        return
    for feature in element.features():
        print feature.name
        print_child_features(feature)

```
However, in my case, I would like to hit the tag `<Placemark>` first, and go back to the parent level to see if some data in `<Placemark>` matches some data in its parent `<Folder>`.  For ex, some kml like this:

```
    <Folder>
        <name>My Selected Sites</name>
        <visibility>0</visibility>
        <Placemark>
          <name>My Selected Sites Pins</name>
          <visibility>0</visibility>
          <styleUrl> ... </styleUrl>
          <LineString>
            <coordinates> ... </coordinates>
          </LineString>
        </Placemark>
      </Folder>
```

That's why `getChild()` and `getParent()` is useful in my case.
