### ISSUE TITLE
Unable to set LineStyle on a Placemark

### ISSUE THREAD

**Issue by nlbutts** [cleder/fastkml#65]
I am trying to adjust the line style for a LineString.  The code is below. I get an error: "TypeError: 'LineStyle' object is not iterable.

        k = kml.KML()
        ns = '{http://www.opengis.net/kml/2.2}'

        # Create a KML Document and add it to the KML root object
        d = kml.Document(ns, 'docid', 'Sherwood', 'Sherwood data')
        k.append(d)

        # Create a Placemark with a simple polygon geometry and add it to the
        # second folder of the Document
        f = kml.Folder(ns, 'fid', 'f name', 'f description')
        d.append(f)

        ls = LineStyle(ns, color='red', width=3)
        p = kml.Placemark(ns, 'id', 'Flight path', styles=ls)
        p.geometry =  LineString(list(longlat))
        f.append(p)

**Comment by mdeyo** [comment]
Also had this issue and couldn't find an answer in the docs. Found out the solution through some trial and error.

```
    ls = LineStyle(ns, color='red', width=3)
    s1 = Style(styles = [ls])
    p = kml.Placemark(ns, 'id', 'Flight path', styles=[s1])
    p.geometry =  LineString(list(longlat))
    f.append(p)
```
The Line Style needs to be added to a Style object and then added to the Placemark. And each 'styles' argument is expecting a list of valid styles, hence the 'object is not iterable' error.
