### ISSUE TITLE
`to_string` may generate invalid KML files

### ISSUE THREAD

**Issue by prusswan** [cleder/fastkml#66]
Not sure if this is specific to my system, but the KML files written cannot be read by other viewers without further modification:

- xml tag is missing (can be added manually)
- tags have extra namespaces (fixed by installing `lxml`)

Tested on http://kmlviewer.nsspot.net/

**Comment by cleder** [comment]
tags having an extra namespace is perfectly valid xml, if the viewer cannot process this it is not processing xml conforming to the specification ;-(

**Comment by prusswan** [comment]
@cleder do you know of other KML validators? I just use that one since it was able to display my source files (but after modifying them with fastkml they became unreadable - until I figured out the differences).

**Comment by cleder** [comment]
I mostly used google earth
