### ISSUE TITLE
Loss of precision when writing geometry with more than 6 decimal places to string

### ISSUE THREAD

**Issue by prusswan** [cleder/fastkml#67]
e.g. `(103.7940492, 1.4391202)` -> `103.794049,1.439120`

In `geometry.py`,  `_etree_coordinates(self, coordinates)` is casting coordinates to `%f`, reducing the values to 6 decimal places.

**Comment by AranVinkItility** [comment]
+1 for this, could not find out why my points where not at the intended point on the map.

**Comment by MShields1986** [comment]
+1

**Comment by cleder** [comment]
PR #98

**Comment by cleder** [comment]
Duplicate of #217

**Comment by cleder** [comment]
Closing this in favour of #217
