### ISSUE TITLE
Example please?

### ISSUE THREAD

**Issue by cbworden** [cleder/fastkml#72]
I've read the documentation, but I'm still unclear one how one can create an element for which there is no predefined function. For instance, can you provide a quick example of how one might implement the <LookAt> or <Camera> element?

**Comment by withoutwaxaryan** [comment]
Could you be more specific??

**Comment by cbworden** [comment]
I created that issue two years ago. I admit that it's vague, especially because I can't recall what I was asking. Maybe someone else knows what I meant? If not, maybe just close the issue and I'll bring it back if I ever get back to KML work.
