### ISSUE TITLE
Adding Altitude mode

### ISSUE THREAD

**Issue by parang17** [cleder/fastkml#76]
I want to add altitude mode ('relativeToGround') in my kml, but I cannot figure it out. Can you help this ? Here is my code.
------------------------------------------------------------------------------
from fastkml import kml
from shapely.geometry import Point, LineString, Polygon
k = kml.KML()
ns = '{http://www.opengis.net/kml/2.2}'

##Create a MKL Document and add it to the KML root object
d = kml.Document(ns, 'ID', 'BIM_path', 'Suwannee_office')
k.append(d)

## Create a KML Folder and add it to the Document
f1 = kml.Folder(ns, 'fid', 'Trajectory', 'f_description')
d.append(f1)

p = kml.Geometry.geometry(ns, id='id', altitude_mode='relativeToGround')
p.geometry = LineString([(-84.038347, 33.999304, 100), (-84.038347, 33.999304, 100),
                           (-84.037679, 33.999255, 100), (-84.037678, 33.999254, 100)])
f1.append(p)

## Print out the KML Object as a string
print(k.to_string(prettyprint=True))
------------------------------------------------------------------------------

**Comment by cleder** [comment]
```
>>> from fastkml import geometry
>>> poi = geometry.Geometry(geometry=geometry.Point(1,1), altitude_mode=='relativeToGround')
>>> poi.to_string()
u'<kml:Point xmlns:kml="http://www.opengis.net/kml/2.2">
   <kml:altitudeMode>relativeToGround</kml:altitudeMode>
   <kml:coordinates>1.000000,1.000000</kml:coordinates>
</kml:Point>
```
