### ISSUE TITLE
Travis-ci: build is failing for amd64 for python:3.4

### ISSUE THREAD

**Issue by sanjaymsh** [cleder/fastkml#91]
Hi,

I am enabling ppc64le build on travis-ci. But its failing on amd64 itself with below error:
"  Complete output from command python setup.py egg_info:
    This lxml version requires Python 2.7, 3.5 or later.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cdxqgk_6/lxml/
The command "if $LXML == true; then pip install lxml; fi" failed and exited with 1 during .
Your build has been stopped."

The full log can be tracked here: https://travis-ci.com/github/sanjaymsh/fastkml/builds/188579445

In my case , i have added both of the arch(amd64 & ppc64le), so its failing on both of the arch for python:3.4 with "LXML=true".

Please have look on this.

Thanks !!

**Comment by dericke** [comment]
Python 3.4 was removed from the travis config in #95. Is there anything else that needs to happen before closing this issue?
